flags: {}
image:
  container:
    base: fpco/stack-run
    name: use-haskell
extra-package-dbs: []
packages:
- .
- location:
    git: https://github.com/Palmik/bson-generic.git
    commit: e078def65d0dee1ea7e3205f445e47d5937851f3
docker:
  enable: false
extra-deps:
- datetime-0.3.1
- git-embed-0.1.0
resolver: nightly-2016-12-10
